branches:
  only:
  - dev

language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
      install:
        - ./installers/install_bazel.sh
      script:
        - bazel test //:protobuf_bytes_unittest
        - bazel run //examples:pointcloud
      after_failure:
        - find bazel-out/ -name "test.log" | xargs cat
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      install:
        - ./installers/install_bazel.sh
      script:
        - bazel test //:protobuf_bytes_unittest
        - bazel run //examples:pointcloud
      after_failure:
        - find bazel-out/ -name "test.log" | xargs cat
    - os: windows
      install:
        - choco install bazel --version 1.2.0
      script:
        - bazel test ///:protobuf_bytes_unittest
        - bazel run ///examples:pointcloud
      after_failure:
        - find bazel-out/ -name "test.log" | xargs cat

notifications:
    email:
        on_success: always
        on_failure: always